"""remove delivery on sms model

Revision ID: a7cd43849b7c
Revises: 37e761628209
Create Date: 2022-08-24 15:11:08.267581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7cd43849b7c'
down_revision = '37e761628209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_column('sms', 'delivery_time')
    op.drop_column('sms', 'sms_units')
    op.drop_column('sms', 'delivery_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms', sa.Column('delivery_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sms', sa.Column('sms_units', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sms', sa.Column('delivery_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
