"""trim down whatsapp model

Revision ID: fbbf091a3678
Revises: 8821a40c02c7
Create Date: 2022-08-19 13:00:39.675097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbbf091a3678'
down_revision = '8821a40c02c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_column('whatsapp_message', 'contact_name')
    op.drop_column('whatsapp_message', 'display_phone_number')
    op.drop_column('whatsapp_message', 'product')
    op.drop_column('whatsapp_message', 'phone_number_id')
    op.drop_column('whatsapp_message', 'whatsapp_id')
    op.drop_column('whatsapp_message', 'general_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_message', sa.Column('general_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('whatsapp_message', sa.Column('whatsapp_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('whatsapp_message', sa.Column('phone_number_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('whatsapp_message', sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('whatsapp_message', sa.Column('display_phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('whatsapp_message', sa.Column('contact_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
